<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMFyBSx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMFyBSx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQMFyBSx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQMFyBSx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQMFyBSx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QMFyBSx',
    'container.build_id' => 'aa02aa5f',
    'container.build_time' => 1746629771,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMFyBSx');
